#app
server:
  port: 8446
  tomcat:
    uri-encoding: utf-8
    # 最大线程数
    max-threads: 10000
    # 最小线程数
    min-spare-threads: 0
    # 队列长度
    accept-count: 10000
    # 最大链接数
    max-connections: 10000
    #链接建立超时时间
    connection-timeout: 10000
    basedir: logTomcat

spring:
  application:
    name: seckill
  profiles:
    active: dev
  #注册到admin服务端
  boot:
    admin:
      client:
        url: http://localhost:8886/admin
#打开actuator监控
management:
  #监控端口
  server:
    port: 8888
  endpoints:
    web:
      #定制跟路径
      base-path: /actuator
      #开放所有节点，默认只开启了health info节点，也可以设置部分启动, 如：env,beans。默认是health, info
      exposure:
        include: "*"
#mybatis
mybatis-plus:
  # xml
  mapper-locations: classpath:mapper/*Mapper.xml
  # 实体扫描，多个package用逗号或者分号分隔
  type-aliases-package: cn.gnosed.shopping.entity
  # 扫描枚举类 # 支持统配符 * 或者 ; 分割
  #  type-enums-package: com.fengwenyi.mybatis_plus_example.enums
  global-config:
    #刷新mapper 调试神器
    db-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: ID_WORKER
      #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      field-strategy: NOT_EMPTY
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置
      logic-delete-value: 1
      logic-not-delete-value: 0
      db-type: mysql
    refresh: true
      #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    #驼峰下划线转换
    map-underscore-to-camel-case: true
    cache-enabled: false

logback:
  appName: seckill
  fileType: log