#spring
spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/shopping?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: "123456"
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      enabled: true
      max-file-size: 300MB
      max-request-size: 1000MB

  #redis
  redis:
    # redis 数据库索引（默认为0）
    database: 3
    # redis 服务地址
    host: 127.0.0.1
    # redis 连接端口
    port: 6379
    # redis 服务器链接密码 （默认为空）
    password:
    # 连接超时时间 （毫秒）
    timeout: 5000
    # 配置 redis 连接池
    jedis:
      pool:
        # 连接池最大连接数　（使用负值表示没有限制）
        max-active: 1000
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 5000
        # 连接池的最大空闲连接
        max-idle: 100
        # 连接池中 最小空闲连接
        min-idle: 0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logback:
  logDir: log/dev

logging:
  level:
    cn.gnosed.shopping: debug